---
title: "Test"
author: "François Mentec"
date: "13 septembre 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyquant)
knitr::opts_chunk$set(echo = TRUE)
```

# DAX 30 analysis

Data are from 10/09/2015 to 10/09/2017

```{r 2y}
df = read.csv("2yDAX.csv", header=TRUE, sep=";")

currentMonth = NULL
open = NULL
high = NULL
low = NULL
close = NULL

dm = data.frame(month=character(),
                open=numeric(),
                high=numeric(),
                low=numeric(),
                close=numeric())

for (i in 1:nrow(df)) {
  month = substr(df[i, "timestamp"], 6, 7)
  if (is.null(currentMonth) || currentMonth != month) {
    if (!is.null(currentMonth)) {
      dm[nrow(dm), ] <- list(month, open, high, low, df[i-1, "close"])
    }
    currentMonth = month
    open = df[i, "open"]
    high = df[i, "high"]
    low = df[i, "low"]
    close = df[i, "close"]
  } else {
    if (df[i, "high"] > high) {
      high = df[i, "high"]
    }
    if (df[i, "low"] < low) {
      low = df[i, "low"]
    }
    close = df[i, "close"]
  }
}

dm

ggplot(data=dm, aes(x=month, y=close)) + geom_candlestick(aes(open=open, high=high, low=low, close=close)) +
  geom_ma(color="darkgreen") +
  theme(axis.text.x=element_text(angle=45, hjust=1), panel.spacing=unit(2, "lines"))

```
ggplot(data=df, aes(x=timestamp, y=close)) + geom_candlestick(aes(open=open, high=high, low=low, close=close)) +
  geom_ma(color="darkgreen") +
  theme(axis.text.x=element_text(angle=45, hjust=1), panel.spacing=unit(2, "lines"))